/**
 * Do not edit directly
 * Generated on Sat, 01 Nov 2025 23:47:26 GMT
 */

export const ColorPrimary50 = "#f0f9ff";
export const ColorPrimary100 = "#e0f2fe";
export const ColorPrimary200 = "#bae6fd";
export const ColorPrimary300 = "#7dd3fc";
export const ColorPrimary400 = "#38bdf8";
export const ColorPrimary500 = "#0ea5e9";
export const ColorPrimary600 = "#0284c7";
export const ColorPrimary700 = "#0369a1";
export const ColorPrimary800 = "#075985";
export const ColorPrimary900 = "#0c4a6e";
export const ColorPrimary950 = "#082f49";
export const ColorNeutral50 = "#f9fafb";
export const ColorNeutral100 = "#f3f4f6";
export const ColorNeutral200 = "#e5e7eb";
export const ColorNeutral300 = "#d1d5db";
export const ColorNeutral400 = "#9ca3af";
export const ColorNeutral500 = "#6b7280";
export const ColorNeutral600 = "#4b5563";
export const ColorNeutral700 = "#374151";
export const ColorNeutral800 = "#1f2937";
export const ColorNeutral900 = "#111827";
export const ColorNeutral950 = "#030712";
export const ColorSuccess50 = "#f0fdf4";
export const ColorSuccess500 = "#22c55e";
export const ColorSuccess900 = "#14532d";
export const ColorError50 = "#fef2f2";
export const ColorError500 = "#ef4444";
export const ColorError900 = "#7f1d1d";
export const ColorWarning50 = "#fffbeb";
export const ColorWarning500 = "#f59e0b";
export const ColorWarning900 = "#78350f";
export const ColorInfo50 = "#eff6ff";
export const ColorInfo100 = "#dbeafe";
export const ColorInfo500 = "#3b82f6";
export const ColorInfo900 = "#1e3a8a";
export const ColorTeal50 = "#f0fdfa";
export const ColorTeal100 = "#ccfbf1";
export const ColorTeal200 = "#99f6e4";
export const ColorTeal300 = "#5eead4";
export const ColorTeal400 = "#2dd4bf";
export const ColorTeal500 = "#14b8a6";
export const ColorTeal600 = "#0d9488";
export const ColorTeal700 = "#0f766e";
export const ColorTeal800 = "#115e59";
export const ColorTeal900 = "#134e4a";
export const ColorTeal950 = "#042f2e";
export const RadiusBase = "0.5rem"; // Base border radius for elements like cards, inputs, buttons
export const ShadowSm = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const ShadowBase = "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)"; // shadcn default shadow
export const ShadowMd = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const ShadowLg = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
export const ShadowXl = "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)";
export const Shadow2xl = "0 25px 50px -12px rgb(0 0 0 / 0.25)";
export const ShadowInner = "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)";
export const SizeXs = "640rem"; // Smallest screen size (Tailwind default)
export const SizeSm = "640rem"; // Small tablet breakpoint (Tailwind sm)
export const SizeMd = "768rem"; // Tablet breakpoint (Tailwind md)
export const SizeLg = "1024rem"; // Laptop breakpoint (Tailwind lg)
export const SizeXl = "1280rem"; // Desktop breakpoint (Tailwind xl)
export const Size2xl = "1400rem"; // Large desktop breakpoint (Tailwind container 2xl)
export const Spacing0 = "0px";
export const Spacing1 = "0.25rem"; // 4px
export const Spacing2 = "0.5rem"; // 8px
export const Spacing3 = "0.75rem"; // 12px
export const Spacing4 = "1rem"; // 16px
export const Spacing5 = "1.25rem"; // 20px
export const Spacing6 = "1.5rem"; // 24px
export const Spacing8 = "2rem"; // 32px
export const Spacing10 = "2.5rem"; // 40px
export const Spacing12 = "3rem"; // 48px
export const Spacing16 = "4rem"; // 64px
export const Spacing20 = "5rem"; // 80px
export const Spacing24 = "6rem"; // 96px
export const FontSizeXs = "0.75rem";
export const FontSizeSm = "0.875rem";
export const FontSizeBase = "1rem";
export const FontSizeLg = "1.125rem";
export const FontSizeXl = "1.25rem";
export const FontSize2xl = "1.5rem";
export const FontSize3xl = "1.875rem";
export const FontSize4xl = "2.25rem";
export const FontSizeAppH1Mobile = "2.25rem";
export const FontSizeAppH1 = "3rem";
export const FontSizeAppH2Mobile = "1.875rem";
export const FontSizeAppH2 = "2.25rem";
export const FontSizeAppH3Mobile = "1.25rem";
export const FontSizeAppH3 = "1.5rem";
export const FontSizeAppBody = "1rem";
export const FontSizeAppSmall = "0.875rem";
export const FontSizeAppCaption = "0.75rem";
export const FontWeightThin = "100";
export const FontWeightExtralight = "200";
export const FontWeightLight = "300";
export const FontWeightNormal = "400";
export const FontWeightMedium = "500";
export const FontWeightSemibold = "600";
export const FontWeightBold = "700";
export const FontWeightExtrabold = "800";
export const FontWeightBlack = "900";
export const LineHeightNone = "1";
export const LineHeightTight = "1.25";
export const LineHeightSnug = "1.375";
export const LineHeightNormal = "1.5";
export const LineHeightRelaxed = "1.625";
export const LineHeightLoose = "2";
export const LetterSpacingTighter = "-0.05em";
export const LetterSpacingTight = "-0.025em";
export const LetterSpacingNormal = "0";
export const LetterSpacingWide = "0.025em";
export const LetterSpacingWider = "0.05em";
export const LetterSpacingWidest = "0.1em";
export const FontFamilySans = "Arial, Helvetica, sans-serif";
export const FontFamilyInter = "Inter, Arial, Helvetica, sans-serif";
export const FontFamilySourceSerifPro = "Source Serif Pro, Georgia, Times New Roman, serif";
export const FontFamilySerif = "Source Serif Pro, Georgia, Times New Roman, serif";
export const FontFamilyMono = "Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace";
export const ThemeColorBackgroundDefault = "#f9fafb";
export const ThemeColorBackgroundMuted = "#f3f4f6";
export const ThemeColorBackgroundSubtle = "#e5e7eb";
export const ThemeColorBackgroundCard = "white";
export const ThemeColorBackgroundDisabled = "#e5e7eb";
export const ThemeColorForegroundDefault = "#111827";
export const ThemeColorForegroundMuted = "#374151";
export const ThemeColorForegroundSubtle = "#6b7280";
export const ThemeColorForegroundDisabled = "#9ca3af";
export const ThemeColorBorderDefault = "#e5e7eb";
export const ThemeColorBorderStrong = "#d1d5db";
export const ThemeColorBorderFocus = "#0ea5e9";
export const ThemeColorPrimaryDefault = "#0d9488";
export const ThemeColorPrimaryHover = "#0f766e";
export const ThemeColorPrimaryForeground = "#f9fafb";
export const ThemeColorPrimaryMuted = "#ccfbf1";
export const ThemeColorSecondaryDefault = "#f3f4f6";
export const ThemeColorSecondaryForeground = "#111827";
export const ThemeColorAccentDefault = "#f3f4f6";
export const ThemeColorAccentForeground = "#111827";
export const ThemeColorSuccessDefault = "#22c55e";
export const ThemeColorSuccessForeground = "white";
export const ThemeColorSuccessMuted = "#f0fdf4";
export const ThemeColorWarningDefault = "#f59e0b";
export const ThemeColorWarningForeground = "white";
export const ThemeColorWarningMuted = "#fffbeb";
export const ThemeColorErrorDefault = "#ef4444";
export const ThemeColorErrorForeground = "white";
export const ThemeColorErrorMuted = "#fef2f2";
export const ThemeColorInfoDefault = "#3b82f6";
export const ThemeColorInfoForeground = "white";
export const ThemeColorInfoMuted = "#eff6ff";
export const ThemeTypographyHeadingFont = "Arial, Helvetica, sans-serif";
export const ThemeTypographyHeadingH1FontSize = "3rem";
export const ThemeTypographyHeadingH1FontWeight = "700";
export const ThemeTypographyHeadingH1LineHeight = "1.25";
export const ThemeTypographyHeadingH2FontSize = "2.25rem";
export const ThemeTypographyHeadingH2FontWeight = "600";
export const ThemeTypographyHeadingH2LineHeight = "1.25";
export const ThemeTypographyHeadingH3FontSize = "1.5rem";
export const ThemeTypographyHeadingH3FontWeight = "600";
export const ThemeTypographyHeadingH3LineHeight = "1.25";
export const ThemeTypographyHeadingH4FontSize = "1rem";
export const ThemeTypographyHeadingH4FontWeight = "600";
export const ThemeTypographyHeadingH4LineHeight = "1.25";
export const ThemeTypographyBodyFont = "Arial, Helvetica, sans-serif";
export const ThemeTypographyBodyLargeFontSize = "1.125rem";
export const ThemeTypographyBodyLargeFontWeight = "400";
export const ThemeTypographyBodyLargeLineHeight = "1.5";
export const ThemeTypographyBodyDefaultFontSize = "1rem";
export const ThemeTypographyBodyDefaultFontWeight = "400";
export const ThemeTypographyBodyDefaultLineHeight = "1.5";
export const ThemeTypographyBodySmallFontSize = "0.875rem";
export const ThemeTypographyBodySmallFontWeight = "400";
export const ThemeTypographyBodySmallLineHeight = "1.5";
export const ThemeTypographyBodyTinyFontSize = "0.75rem";
export const ThemeTypographyBodyTinyFontWeight = "400";
export const ThemeTypographyBodyTinyLineHeight = "1.5";
export const ThemeSizeContainerXs = "640rem";
export const ThemeSizeContainerSm = "640rem";
export const ThemeSizeContainerMd = "768rem";
export const ThemeSizeContainerLg = "1024rem";
export const ThemeSizeContainerXl = "1280rem";
export const ThemeSizeContainer2xl = "1400rem";
export const ThemeSizeInputHeight = "2.5rem";
export const ThemeSizeInputSm = "2rem";
export const ThemeSizeInputLg = "3rem";
export const ThemeSizeIconSm = "1rem";
export const ThemeSizeIconMd = "1.5rem";
export const ThemeSizeIconLg = "2rem";
export const ThemeSpaceComponentXs = "0.25rem";
export const ThemeSpaceComponentSm = "0.5rem";
export const ThemeSpaceComponentMd = "1rem";
export const ThemeSpaceComponentLg = "1.5rem";
export const ThemeSpaceComponentXl = "2rem";
export const ThemeSpaceLayoutXs = "0.5rem";
export const ThemeSpaceLayoutSm = "1rem";
export const ThemeSpaceLayoutMd = "1.5rem";
export const ThemeSpaceLayoutLg = "2rem";
export const ThemeSpaceLayoutXl = "4rem";
export const ThemeSpaceLayout2xl = "6rem";
export const ThemeSpaceGridBase = "1rem";
export const ThemeElevationLow = "0 1px 2px 0 rgb(0 0 0 / 0.05)";
export const ThemeElevationMedium = "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)";
export const ThemeElevationHigh = "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)";
export const ThemeElevationHigher = "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)";
export const ThemeElevationHighest = "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)";
